name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read # needed for only-new-issues option below

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
     - name: harden runner
       uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
       with:
         egress-policy: block
         disable-sudo: true
         allowed-endpoints: >
           github.com:443
           api.github.com:443
           proxy.github.com:443
           proxy.golang.org:443
           raw.githubusercontent.com:443
           objects.githubusercontent.com:443
           proxy.golang.org:443
           storage.googleapis.com:443
           release-assets.githubusercontent.com:443
     - name: checkout code
       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
     - name: setup go
       uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
       with:
         go-version: 1.26
     - name: lint
       uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
       with:
         version: v2.11
         args: --timeout=5m0s --verbose
         only-new-issues: true
